### ISSUE TITLE
4/15

### ISSUE THREAD

**Issue by mjlee108** [mjlee108/vujade#6]
HTML 실습
개발도구
CSS 이론
CSS 실습
프로그래밍
복습과 수업예고
자바스크립트 vs PHP
웹페이지에 코드 삽입하기
데이터타입과 연산자
디버깅
변수
비교
조건문
로그인 기능 만들기
반복문

**Comment by 0duru1** [comment]
@mjlee108 보고 이해하는 것도 중요하지만 코드를 직접 입력해보면서 감을 잡아보는 것도 좋으실 것 같아요~~ 굿잡
